seed: 123456789
device: cuda:0
val_size: 0.01
test_size: 0.02
mini_batch_size: 256
lr: 1.0e-3
weight_decay: 1.0e-6
val_patience: 50
val_tolerance: 1.0e-4
max_epochs: 200
validation_freq: 10
checkpoint_freq: 10000
algorithm: distmult
loader_hpars:
  dataset_name: wordnet
  sample_source: smore
  sampler_hpars:
    num_negative_samples: 128
    num_neighbours: 10
    random_walk_length: 10
    context_radius: 2
    pagerank_importances: true
    walks_relation_specific: true
embedder_hpars:
  embedding_dim: 100
link_ranker_hpars:
  algorithm: distmult
embedding_loss_hpars:
  margin: 1.0
  rotate_alpha: 0.5
